name: Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Tag
        run: |
          git config --global user.name 'Martin'
          git config --global user.email 'martin.braquet@users.noreply.github.com'
          chmod +x ./tag.sh
          ./tag.sh
